server:
  port: 8091
logging:
  level: DEBUG
spring:
  profiles: 
    active: '@profileActive@'
  messages:
    basename: message/resource,message/lookup
    cache-seconds: ${args.messages.cache-seconds:5}
  datasource:
    url: ${args.datasource.url:jdbc:mysql://localhost:8099/yqyl_business?characterEncoding=utf-8}
    username: ${args.datasource.username:dev}
    password: ${args.datasource.password:!QAZ2wsx}
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: select 1
    sqlScriptEncoding: utf-8
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

---
spring: 
  profiles: qa
args:
  messages: 
    cache-seconds: -1
  datasource: 
    url: jdbc:mysql://localhost:8099/yqyl_business?characterEncoding=utf-8
    
---
spring: 
  profiles: dev-home
args:
  datasource: 
    url: jdbc:mysql://localhost:3306/yqyl_business?characterEncoding=utf-8
     
---
spring: 
  profiles: dev-work
args:
  datasource: 
    url: jdbc:mysql://172.16.128.191:3307/yqyl_business?characterEncoding=utf-8
    username: qa 