server: 
  port: 60824
eureka: 
  instance: 
    hostname: discovery
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://localhost:60824/eureka/
    